verify broker name is in lower case letters
Peripli/service-broker-proxy-k8s pull request #109
Opened 2020-10-27 09:33 UTC by evyaffe

Justification: k8s cannot register brokers with names containing capital letters

2020-10-27 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Peripli/service-broker-proxy-k8s?pullRequest=109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Peripli/service-broker-proxy-k8s?pullRequest=109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Peripli/service-broker-proxy-k8s?pullRequest=109) it.</sub>

2020-10-27 21:11 UTC, pavelmaliy approved these changes

2020-10-28 20:29 UTC, eyalnathan requested changes
I think this causes an issue with the take over logic during reconciliation - see where GetBrokers is used, the name is used as a map key and then the code uses the name from SM for lookups in the map and it won't work as the name are not equal (capital vs. lower case).

2020-11-08 08:10 UTC, eyalnathan submitted a review, later dismissed
Looks good, but please update the dependencies to service-broker-proxy to master (or new release) before merging

2020-11-09 07:17 UTC, idobergerfroind approved these changes

2020-11-09 07:19 UTC, merged